:defaults: &defaults
  test: true
  gateway: braintree
  login: testapi
  password: password1
  
  plans:
    - name: basic
      interval: <%= 1.month %>
      currency: USD
      price: 2400
    - name: plus
      interval: <%= 1.month %>
      currency: USD
      price: 4900
    - name: premium
      interval: <%= 1.month %>
      currency: USD
      price: 9900
    - name: max
      interval: <%= 1.month %>
      currency: USD
      price: 14900
    
:development:
  <<: *defaults

:test:
  <<: *defaults

:production:
  <<: *defaults
  
  test: false